apiVersion: apps/v1
kind: Deployment
metadata:
  name: target
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: target
  template:
    metadata:
      labels:
        app: target
    spec:
      containers:
        - image: 972062722764.dkr.ecr.us-east-2.amazonaws.com/dangerious-vulnerable:latest
        name: target
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: '50Mi'
            cpu: '200m'
          limits:
            memory: '128Mi'
            cpu: '1000m'
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
